version: "3.9"
services: 
  test:
    image: "exercise-7"
    volumes:
    - .:/app
    command: python3 -m pytest
  run: 
    image: "exercise-7"
    volumes:
    - .:/app
    command: python3 main.py